var annotated_dup =
[
    [ "audio_file", null, [
      [ "audio_file", "structaudio__file_1_1audio__file.html", "structaudio__file_1_1audio__file" ]
    ] ],
    [ "detail", null, [
      [ "any", "structdetail_1_1any.html", null ],
      [ "any< T >", "structdetail_1_1any_3_01_t_01_4.html", null ],
      [ "any< T, Ts... >", "structdetail_1_1any_3_01_t_00_01_ts_8_8_8_01_4.html", null ],
      [ "cl_vector_constructor", "structdetail_1_1cl__vector__constructor.html", null ],
      [ "cl_vector_constructor< bool, N >", "structdetail_1_1cl__vector__constructor_3_01bool_00_01_n_01_4.html", "structdetail_1_1cl__vector__constructor_3_01bool_00_01_n_01_4" ],
      [ "cl_vector_type_trait", "structdetail_1_1cl__vector__type__trait.html", "structdetail_1_1cl__vector__type__trait" ],
      [ "max_functor", "structdetail_1_1max__functor.html", "structdetail_1_1max__functor" ],
      [ "min_functor", "structdetail_1_1min__functor.html", "structdetail_1_1min__functor" ]
    ] ],
    [ "frequency_domain", null, [
      [ "buffer", "classfrequency__domain_1_1buffer.html", "classfrequency__domain_1_1buffer" ],
      [ "convolver", "classfrequency__domain_1_1convolver.html", "classfrequency__domain_1_1convolver" ],
      [ "dft_1d", "classfrequency__domain_1_1dft__1d.html", "classfrequency__domain_1_1dft__1d" ],
      [ "edges_and_width_factor", "structfrequency__domain_1_1edges__and__width__factor.html", "structfrequency__domain_1_1edges__and__width__factor" ],
      [ "filter", "classfrequency__domain_1_1filter.html", "classfrequency__domain_1_1filter" ],
      [ "indexer", "classfrequency__domain_1_1indexer.html", "classfrequency__domain_1_1indexer" ],
      [ "make_indexer_iterator", "structfrequency__domain_1_1make__indexer__iterator.html", "structfrequency__domain_1_1make__indexer__iterator" ],
      [ "plan", "classfrequency__domain_1_1plan.html", "classfrequency__domain_1_1plan" ],
      [ "type_trait", "structfrequency__domain_1_1type__trait.html", null ],
      [ "type_trait< fftwf_complex >", "structfrequency__domain_1_1type__trait_3_01fftwf__complex_01_4.html", "structfrequency__domain_1_1type__trait_3_01fftwf__complex_01_4" ],
      [ "type_trait< float >", "structfrequency__domain_1_1type__trait_3_01float_01_4.html", "structfrequency__domain_1_1type__trait_3_01float_01_4" ]
    ] ],
    [ "hrtf_data", null, [
      [ "entry", "structhrtf__data_1_1entry.html", "structhrtf__data_1_1entry" ]
    ] ],
    [ "raytracer", null, [
      [ "img_src_calculation", "structraytracer_1_1img__src__calculation.html", "structraytracer_1_1img__src__calculation" ]
    ] ],
    [ "testing", null, [
      [ "kernel", "classtesting_1_1kernel.html", "classtesting_1_1kernel" ],
      [ "testing_rk_biquad", "classtesting_1_1testing__rk__biquad.html", null ],
      [ "testing_rk_biquad_quiet", "classtesting_1_1testing__rk__biquad__quiet.html", null ],
      [ "testing_rk_filter", "classtesting_1_1testing__rk__filter.html", null ],
      [ "testing_rk_filter_quiet", "classtesting_1_1testing__rk__filter__quiet.html", null ]
    ] ],
    [ "util", null, [
      [ "aligned", null, [
        [ "allocator", "classutil_1_1aligned_1_1allocator.html", "classutil_1_1aligned_1_1allocator" ]
      ] ],
      [ "threading_policy", null, [
        [ "no_lock", "classutil_1_1threading__policy_1_1no__lock.html", "classutil_1_1threading__policy_1_1no__lock" ],
        [ "scoped_lock", "classutil_1_1threading__policy_1_1scoped__lock.html", "classutil_1_1threading__policy_1_1scoped__lock" ]
      ] ],
      [ "Bracketer", "structutil_1_1_bracketer.html", "structutil_1_1_bracketer" ],
      [ "event", "classutil_1_1event.html", "classutil_1_1event" ],
      [ "identity_functor", "structutil_1_1identity__functor.html", "structutil_1_1identity__functor" ],
      [ "is_tuple", "structutil_1_1is__tuple.html", "structutil_1_1is__tuple" ],
      [ "is_tuple< std::tuple< Ts... > >", "structutil_1_1is__tuple_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", "structutil_1_1is__tuple_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4" ],
      [ "mapping_iterator_adapter", "classutil_1_1mapping__iterator__adapter.html", "classutil_1_1mapping__iterator__adapter" ],
      [ "named_value", "structutil_1_1named__value.html", "structutil_1_1named__value" ],
      [ "progress_bar", "classutil_1_1progress__bar.html", "classutil_1_1progress__bar" ],
      [ "range", "classutil_1_1range.html", "classutil_1_1range" ],
      [ "scoped_thread", "classutil_1_1scoped__thread.html", "classutil_1_1scoped__thread" ],
      [ "threaded_queue", "classutil_1_1threaded__queue.html", "classutil_1_1threaded__queue" ],
      [ "tuple_like_size", "structutil_1_1tuple__like__size.html", null ],
      [ "tuple_like_size< std::array< T, I > >", "structutil_1_1tuple__like__size_3_01std_1_1array_3_01_t_00_01_i_01_4_01_4.html", "structutil_1_1tuple__like__size_3_01std_1_1array_3_01_t_00_01_i_01_4_01_4" ],
      [ "tuple_like_size< std::tuple< Ts... > >", "structutil_1_1tuple__like__size_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", "structutil_1_1tuple__like__size_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4" ],
      [ "tuple_like_size< T[I]>", "structutil_1_1tuple__like__size_3_01_t[_i]_4.html", "structutil_1_1tuple__like__size_3_01_t[_i]_4" ]
    ] ],
    [ "wayverb", null, [
      [ "combined", null, [
        [ "model", null, [
          [ "presets", null, [
            [ "capsule", "structwayverb_1_1combined_1_1model_1_1presets_1_1capsule.html", "structwayverb_1_1combined_1_1model_1_1presets_1_1capsule" ]
          ] ],
          [ "basic_member", "classwayverb_1_1combined_1_1model_1_1basic__member.html", "classwayverb_1_1combined_1_1model_1_1basic__member" ],
          [ "capsule", "classwayverb_1_1combined_1_1model_1_1capsule.html", "classwayverb_1_1combined_1_1model_1_1capsule" ],
          [ "hover_state", "classwayverb_1_1combined_1_1model_1_1hover__state.html", "classwayverb_1_1combined_1_1model_1_1hover__state" ],
          [ "hrtf", "classwayverb_1_1combined_1_1model_1_1hrtf.html", "classwayverb_1_1combined_1_1model_1_1hrtf" ],
          [ "item_extractor", "structwayverb_1_1combined_1_1model_1_1item__extractor.html", "structwayverb_1_1combined_1_1model_1_1item__extractor" ],
          [ "material", "classwayverb_1_1combined_1_1model_1_1material.html", "classwayverb_1_1combined_1_1model_1_1material" ],
          [ "microphone", "classwayverb_1_1combined_1_1model_1_1microphone.html", "classwayverb_1_1combined_1_1model_1_1microphone" ],
          [ "min_size_vector", "classwayverb_1_1combined_1_1model_1_1min__size__vector.html", "classwayverb_1_1combined_1_1model_1_1min__size__vector" ],
          [ "multiple_band_waveguide", "classwayverb_1_1combined_1_1model_1_1multiple__band__waveguide.html", "classwayverb_1_1combined_1_1model_1_1multiple__band__waveguide" ],
          [ "output", "classwayverb_1_1combined_1_1model_1_1output.html", "classwayverb_1_1combined_1_1model_1_1output" ],
          [ "owning_member", "classwayverb_1_1combined_1_1model_1_1owning__member.html", "classwayverb_1_1combined_1_1model_1_1owning__member" ],
          [ "persistent", "classwayverb_1_1combined_1_1model_1_1persistent.html", "classwayverb_1_1combined_1_1model_1_1persistent" ],
          [ "persistent_connection", "classwayverb_1_1combined_1_1model_1_1persistent__connection.html", "classwayverb_1_1combined_1_1model_1_1persistent__connection" ],
          [ "raytracer", "classwayverb_1_1combined_1_1model_1_1raytracer.html", "classwayverb_1_1combined_1_1model_1_1raytracer" ],
          [ "receiver", "classwayverb_1_1combined_1_1model_1_1receiver.html", "classwayverb_1_1combined_1_1model_1_1receiver" ],
          [ "scene", "classwayverb_1_1combined_1_1model_1_1scene.html", "classwayverb_1_1combined_1_1model_1_1scene" ],
          [ "single_band_waveguide", "classwayverb_1_1combined_1_1model_1_1single__band__waveguide.html", "classwayverb_1_1combined_1_1model_1_1single__band__waveguide" ],
          [ "source", "classwayverb_1_1combined_1_1model_1_1source.html", "classwayverb_1_1combined_1_1model_1_1source" ],
          [ "vector", "classwayverb_1_1combined_1_1model_1_1vector.html", "classwayverb_1_1combined_1_1model_1_1vector" ],
          [ "view_state", "classwayverb_1_1combined_1_1model_1_1view__state.html", "classwayverb_1_1combined_1_1model_1_1view__state" ],
          [ "waveguide", "classwayverb_1_1combined_1_1model_1_1waveguide.html", "classwayverb_1_1combined_1_1model_1_1waveguide" ]
        ] ],
        [ "capsule", "classwayverb_1_1combined_1_1capsule.html", "classwayverb_1_1combined_1_1capsule" ],
        [ "capsule_base", "classwayverb_1_1combined_1_1capsule__base.html", "classwayverb_1_1combined_1_1capsule__base" ],
        [ "combined_results", "structwayverb_1_1combined_1_1combined__results.html", "structwayverb_1_1combined_1_1combined__results" ],
        [ "complete_engine", "classwayverb_1_1combined_1_1complete__engine.html", "classwayverb_1_1combined_1_1complete__engine" ],
        [ "concrete_waveguide", "classwayverb_1_1combined_1_1concrete__waveguide.html", "classwayverb_1_1combined_1_1concrete__waveguide" ],
        [ "engine", "classwayverb_1_1combined_1_1engine.html", "classwayverb_1_1combined_1_1engine" ],
        [ "forwarding_call", "classwayverb_1_1combined_1_1forwarding__call.html", "classwayverb_1_1combined_1_1forwarding__call" ],
        [ "intermediate", "classwayverb_1_1combined_1_1intermediate.html", "classwayverb_1_1combined_1_1intermediate" ],
        [ "max_frequency_functor", "structwayverb_1_1combined_1_1max__frequency__functor.html", "structwayverb_1_1combined_1_1max__frequency__functor" ],
        [ "postprocessing_engine", "classwayverb_1_1combined_1_1postprocessing__engine.html", "classwayverb_1_1combined_1_1postprocessing__engine" ],
        [ "waveguide_base", "classwayverb_1_1combined_1_1waveguide__base.html", "classwayverb_1_1combined_1_1waveguide__base" ]
      ] ],
      [ "core", null, [
        [ "attenuator", null, [
          [ "hrtf", "classwayverb_1_1core_1_1attenuator_1_1hrtf.html", "classwayverb_1_1core_1_1attenuator_1_1hrtf" ],
          [ "microphone", "classwayverb_1_1core_1_1attenuator_1_1microphone.html", "classwayverb_1_1core_1_1attenuator_1_1microphone" ],
          [ "null", "classwayverb_1_1core_1_1attenuator_1_1null.html", null ]
        ] ],
        [ "detail", null, [
          [ "cl_type_index_mapper", "classwayverb_1_1core_1_1detail_1_1cl__type__index__mapper.html", "classwayverb_1_1core_1_1detail_1_1cl__type__index__mapper" ],
          [ "range_value", "structwayverb_1_1core_1_1detail_1_1range__value.html", null ],
          [ "range_value< 1 >", "structwayverb_1_1core_1_1detail_1_1range__value_3_011_01_4.html", "structwayverb_1_1core_1_1detail_1_1range__value_3_011_01_4" ],
          [ "range_value< 2 >", "structwayverb_1_1core_1_1detail_1_1range__value_3_012_01_4.html", "structwayverb_1_1core_1_1detail_1_1range__value_3_012_01_4" ],
          [ "range_value< 3 >", "structwayverb_1_1core_1_1detail_1_1range__value_3_013_01_4.html", "structwayverb_1_1core_1_1detail_1_1range__value_3_013_01_4" ],
          [ "recursive_vector_impl", "classwayverb_1_1core_1_1detail_1_1recursive__vector__impl.html", "classwayverb_1_1core_1_1detail_1_1recursive__vector__impl" ],
          [ "voxel_data_trait", "structwayverb_1_1core_1_1detail_1_1voxel__data__trait.html", "structwayverb_1_1core_1_1detail_1_1voxel__data__trait" ],
          [ "voxel_data_trait< 0 >", "structwayverb_1_1core_1_1detail_1_1voxel__data__trait_3_010_01_4.html", "structwayverb_1_1core_1_1detail_1_1voxel__data__trait_3_010_01_4" ]
        ] ],
        [ "exceptions", null, [
          [ "exception", "classwayverb_1_1core_1_1exceptions_1_1exception.html", "classwayverb_1_1core_1_1exceptions_1_1exception" ],
          [ "suspicious_value", "classwayverb_1_1core_1_1exceptions_1_1suspicious__value.html", "classwayverb_1_1core_1_1exceptions_1_1suspicious__value" ],
          [ "value_is_inf", "classwayverb_1_1core_1_1exceptions_1_1value__is__inf.html", null ],
          [ "value_is_nan", "classwayverb_1_1core_1_1exceptions_1_1value__is__nan.html", null ]
        ] ],
        [ "filter", null, [
          [ "bandpass_windowed_sinc", "classwayverb_1_1core_1_1filter_1_1bandpass__windowed__sinc.html", "classwayverb_1_1core_1_1filter_1_1bandpass__windowed__sinc" ],
          [ "biquad", "classwayverb_1_1core_1_1filter_1_1biquad.html", "classwayverb_1_1core_1_1filter_1_1biquad" ],
          [ "delay_line", "classwayverb_1_1core_1_1filter_1_1delay__line.html", "classwayverb_1_1core_1_1filter_1_1delay__line" ],
          [ "extra_linear_dc_blocker", "classwayverb_1_1core_1_1filter_1_1extra__linear__dc__blocker.html", "classwayverb_1_1core_1_1filter_1_1extra__linear__dc__blocker" ],
          [ "hipass_windowed_sinc", "classwayverb_1_1core_1_1filter_1_1hipass__windowed__sinc.html", "classwayverb_1_1core_1_1filter_1_1hipass__windowed__sinc" ],
          [ "linear_dc_blocker", "classwayverb_1_1core_1_1filter_1_1linear__dc__blocker.html", "classwayverb_1_1core_1_1filter_1_1linear__dc__blocker" ],
          [ "lopass_windowed_sinc", "classwayverb_1_1core_1_1filter_1_1lopass__windowed__sinc.html", "classwayverb_1_1core_1_1filter_1_1lopass__windowed__sinc" ],
          [ "moving_average", "classwayverb_1_1core_1_1filter_1_1moving__average.html", "classwayverb_1_1core_1_1filter_1_1moving__average" ],
          [ "n_moving_averages", "classwayverb_1_1core_1_1filter_1_1n__moving__averages.html", "classwayverb_1_1core_1_1filter_1_1n__moving__averages" ],
          [ "series_biquads", "classwayverb_1_1core_1_1filter_1_1series__biquads.html", "classwayverb_1_1core_1_1filter_1_1series__biquads" ]
        ] ],
        [ "geo", null, [
          [ "detail", null, [
            [ "projection_2d", "structwayverb_1_1core_1_1geo_1_1detail_1_1projection__2d.html", "structwayverb_1_1core_1_1geo_1_1detail_1_1projection__2d" ]
          ] ],
          [ "ray", "classwayverb_1_1core_1_1geo_1_1ray.html", "classwayverb_1_1core_1_1geo_1_1ray" ],
          [ "triangle_vec3", "structwayverb_1_1core_1_1geo_1_1triangle__vec3.html", "structwayverb_1_1core_1_1geo_1_1triangle__vec3" ]
        ] ],
        [ "hrtf_look_up_table", null, [
          [ "azimuth_functor", "structwayverb_1_1core_1_1hrtf__look__up__table_1_1azimuth__functor.html", "structwayverb_1_1core_1_1hrtf__look__up__table_1_1azimuth__functor" ],
          [ "elevation_functor", "structwayverb_1_1core_1_1hrtf__look__up__table_1_1elevation__functor.html", "structwayverb_1_1core_1_1hrtf__look__up__table_1_1elevation__functor" ]
        ] ],
        [ "indexing", null, [
          [ "index", "structwayverb_1_1core_1_1indexing_1_1index.html", null ],
          [ "index< 1 >", "structwayverb_1_1core_1_1indexing_1_1index_3_011_01_4.html", "structwayverb_1_1core_1_1indexing_1_1index_3_011_01_4" ],
          [ "index< 2 >", "structwayverb_1_1core_1_1indexing_1_1index_3_012_01_4.html", "structwayverb_1_1core_1_1indexing_1_1index_3_012_01_4" ],
          [ "index< 3 >", "structwayverb_1_1core_1_1indexing_1_1index_3_013_01_4.html", "structwayverb_1_1core_1_1indexing_1_1index_3_013_01_4" ]
        ] ],
        [ "aabb", "structwayverb_1_1core_1_1aabb.html", "structwayverb_1_1core_1_1aabb" ],
        [ "az_el", "structwayverb_1_1core_1_1az__el.html", "structwayverb_1_1core_1_1az__el" ],
        [ "callback_accumulator", "classwayverb_1_1core_1_1callback__accumulator.html", "classwayverb_1_1core_1_1callback__accumulator" ],
        [ "cl_representation", "structwayverb_1_1core_1_1cl__representation.html", null ],
        [ "cl_representation< aabb >", "structwayverb_1_1core_1_1cl__representation_3_01aabb_01_4.html", null ],
        [ "cl_representation< bands_type >", "structwayverb_1_1core_1_1cl__representation_3_01bands__type_01_4.html", null ],
        [ "cl_representation< intersection >", "structwayverb_1_1core_1_1cl__representation_3_01intersection_01_4.html", null ],
        [ "cl_representation< ray >", "structwayverb_1_1core_1_1cl__representation_3_01ray_01_4.html", null ],
        [ "cl_representation< raytracer::attenuated_impulse< 8 > >", "structwayverb_1_1core_1_1cl__representation_3_01raytracer_1_1attenuated__impulse_3_018_01_4_01_4.html", null ],
        [ "cl_representation< raytracer::impulse< 8 > >", "structwayverb_1_1core_1_1cl__representation_3_01raytracer_1_1impulse_3_018_01_4_01_4.html", null ],
        [ "cl_representation< raytracer::reflection >", "structwayverb_1_1core_1_1cl__representation_3_01raytracer_1_1reflection_01_4.html", null ],
        [ "cl_representation< raytracer::stochastic_path_info >", "structwayverb_1_1core_1_1cl__representation_3_01raytracer_1_1stochastic__path__info_01_4.html", null ],
        [ "cl_representation< surface< simulation_bands > >", "structwayverb_1_1core_1_1cl__representation_3_01surface_3_01simulation__bands_01_4_01_4.html", null ],
        [ "cl_representation< triangle >", "structwayverb_1_1core_1_1cl__representation_3_01triangle_01_4.html", null ],
        [ "cl_representation< triangle_inter >", "structwayverb_1_1core_1_1cl__representation_3_01triangle__inter_01_4.html", null ],
        [ "cl_representation< triangle_verts >", "structwayverb_1_1core_1_1cl__representation_3_01triangle__verts_01_4.html", null ],
        [ "cl_representation< waveguide::biquad_coefficients_array >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1biquad__coefficients__array_01_4.html", null ],
        [ "cl_representation< waveguide::biquad_memory_array >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1biquad__memory__array_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_data >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__data_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_data_array_1 >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__data__array__1_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_data_array_2 >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__data__array__2_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_data_array_3 >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__data__array__3_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_index_array_1 >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__index__array__1_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_index_array_2 >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__index__array__2_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_index_array_3 >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__index__array__3_01_4.html", null ],
        [ "cl_representation< waveguide::boundary_type >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1boundary__type_01_4.html", null ],
        [ "cl_representation< waveguide::coefficients_biquad >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1coefficients__biquad_01_4.html", null ],
        [ "cl_representation< waveguide::coefficients_canonical >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1coefficients__canonical_01_4.html", null ],
        [ "cl_representation< waveguide::condensed_node >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1condensed__node_01_4.html", null ],
        [ "cl_representation< waveguide::error_code >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1error__code_01_4.html", null ],
        [ "cl_representation< waveguide::filt_real >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1filt__real_01_4.html", null ],
        [ "cl_representation< waveguide::memory_biquad >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1memory__biquad_01_4.html", null ],
        [ "cl_representation< waveguide::memory_canonical >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1memory__canonical_01_4.html", null ],
        [ "cl_representation< waveguide::mesh_descriptor >", "structwayverb_1_1core_1_1cl__representation_3_01waveguide_1_1mesh__descriptor_01_4.html", null ],
        [ "compute_context", "classwayverb_1_1core_1_1compute__context.html", "classwayverb_1_1core_1_1compute__context" ],
        [ "cosine_interp_functor", "structwayverb_1_1core_1_1cosine__interp__functor.html", "structwayverb_1_1core_1_1cosine__interp__functor" ],
        [ "direction_rng", "classwayverb_1_1core_1_1direction__rng.html", "classwayverb_1_1core_1_1direction__rng" ],
        [ "environment", "structwayverb_1_1core_1_1environment.html", "structwayverb_1_1core_1_1environment" ],
        [ "filter_coefficients", "structwayverb_1_1core_1_1filter__coefficients.html", "structwayverb_1_1core_1_1filter__coefficients" ],
        [ "generic_scene_buffers", "classwayverb_1_1core_1_1generic__scene__buffers.html", "classwayverb_1_1core_1_1generic__scene__buffers" ],
        [ "generic_scene_data", "classwayverb_1_1core_1_1generic__scene__data.html", "classwayverb_1_1core_1_1generic__scene__data" ],
        [ "intersection", "structwayverb_1_1core_1_1intersection.html", "structwayverb_1_1core_1_1intersection" ],
        [ "item_and_index", "structwayverb_1_1core_1_1item__and__index.html", "structwayverb_1_1core_1_1item__and__index" ],
        [ "linear_interp_functor", "structwayverb_1_1core_1_1linear__interp__functor.html", "structwayverb_1_1core_1_1linear__interp__functor" ],
        [ "linear_regression", "structwayverb_1_1core_1_1linear__regression.html", "structwayverb_1_1core_1_1linear__regression" ],
        [ "ndim_tree", "classwayverb_1_1core_1_1ndim__tree.html", "classwayverb_1_1core_1_1ndim__tree" ],
        [ "orientation", "classwayverb_1_1core_1_1orientation.html", "classwayverb_1_1core_1_1orientation" ],
        [ "program_wrapper", "classwayverb_1_1core_1_1program__wrapper.html", "classwayverb_1_1core_1_1program__wrapper" ],
        [ "ray", "structwayverb_1_1core_1_1ray.html", "structwayverb_1_1core_1_1ray" ],
        [ "recursive_vector", "classwayverb_1_1core_1_1recursive__vector.html", "classwayverb_1_1core_1_1recursive__vector" ],
        [ "recursive_vector_backed_set", "classwayverb_1_1core_1_1recursive__vector__backed__set.html", "classwayverb_1_1core_1_1recursive__vector__backed__set" ],
        [ "reverb_time", "structwayverb_1_1core_1_1reverb__time.html", "structwayverb_1_1core_1_1reverb__time" ],
        [ "scene_data_loader", "classwayverb_1_1core_1_1scene__data__loader.html", "classwayverb_1_1core_1_1scene__data__loader" ],
        [ "surface", "structwayverb_1_1core_1_1surface.html", "structwayverb_1_1core_1_1surface" ],
        [ "to_cl_float3", "structwayverb_1_1core_1_1to__cl__float3.html", "structwayverb_1_1core_1_1to__cl__float3" ],
        [ "to_cl_int3", "structwayverb_1_1core_1_1to__cl__int3.html", "structwayverb_1_1core_1_1to__cl__int3" ],
        [ "to_ivec2", "structwayverb_1_1core_1_1to__ivec2.html", "structwayverb_1_1core_1_1to__ivec2" ],
        [ "to_ivec3", "structwayverb_1_1core_1_1to__ivec3.html", "structwayverb_1_1core_1_1to__ivec3" ],
        [ "to_vec2", "structwayverb_1_1core_1_1to__vec2.html", "structwayverb_1_1core_1_1to__vec2" ],
        [ "to_vec3", "structwayverb_1_1core_1_1to__vec3.html", "structwayverb_1_1core_1_1to__vec3" ],
        [ "triangle", "structwayverb_1_1core_1_1triangle.html", "structwayverb_1_1core_1_1triangle" ],
        [ "triangle_inter", "structwayverb_1_1core_1_1triangle__inter.html", "structwayverb_1_1core_1_1triangle__inter" ],
        [ "triangle_verts", "structwayverb_1_1core_1_1triangle__verts.html", "structwayverb_1_1core_1_1triangle__verts" ],
        [ "unit_constructor", "structwayverb_1_1core_1_1unit__constructor.html", null ],
        [ "unit_constructor< cl_float1 >", "structwayverb_1_1core_1_1unit__constructor_3_01cl__float1_01_4.html", null ],
        [ "unit_constructor< cl_float2 >", "structwayverb_1_1core_1_1unit__constructor_3_01cl__float2_01_4.html", null ],
        [ "unit_constructor< cl_float4 >", "structwayverb_1_1core_1_1unit__constructor_3_01cl__float4_01_4.html", null ],
        [ "unit_constructor< cl_float8 >", "structwayverb_1_1core_1_1unit__constructor_3_01cl__float8_01_4.html", null ],
        [ "unit_constructor< float >", "structwayverb_1_1core_1_1unit__constructor_3_01float_01_4.html", null ],
        [ "vector_look_up_table", "structwayverb_1_1core_1_1vector__look__up__table.html", "structwayverb_1_1core_1_1vector__look__up__table" ],
        [ "voxel_collection", "classwayverb_1_1core_1_1voxel__collection.html", "classwayverb_1_1core_1_1voxel__collection" ],
        [ "voxelised_scene_data", "classwayverb_1_1core_1_1voxelised__scene__data.html", "classwayverb_1_1core_1_1voxelised__scene__data" ]
      ] ],
      [ "raytracer", null, [
        [ "image_source", null, [
          [ "fast_pressure_calculator", "classwayverb_1_1raytracer_1_1image__source_1_1fast__pressure__calculator.html", "classwayverb_1_1raytracer_1_1image__source_1_1fast__pressure__calculator" ],
          [ "path_element", "structwayverb_1_1raytracer_1_1image__source_1_1path__element.html", "structwayverb_1_1raytracer_1_1image__source_1_1path__element" ],
          [ "reflection_metadata", "structwayverb_1_1raytracer_1_1image__source_1_1reflection__metadata.html", "structwayverb_1_1raytracer_1_1image__source_1_1reflection__metadata" ],
          [ "reflection_path_builder", "classwayverb_1_1raytracer_1_1image__source_1_1reflection__path__builder.html", "classwayverb_1_1raytracer_1_1image__source_1_1reflection__path__builder" ],
          [ "traversal_callback", "classwayverb_1_1raytracer_1_1image__source_1_1traversal__callback.html", "classwayverb_1_1raytracer_1_1image__source_1_1traversal__callback" ],
          [ "tree", "classwayverb_1_1raytracer_1_1image__source_1_1tree.html", "classwayverb_1_1raytracer_1_1image__source_1_1tree" ]
        ] ],
        [ "reflection_processor", null, [
          [ "energy_histogram_sum_functor", "structwayverb_1_1raytracer_1_1reflection__processor_1_1energy__histogram__sum__functor.html", "structwayverb_1_1raytracer_1_1reflection__processor_1_1energy__histogram__sum__functor" ],
          [ "image_source", "classwayverb_1_1raytracer_1_1reflection__processor_1_1image__source.html", "classwayverb_1_1raytracer_1_1reflection__processor_1_1image__source" ],
          [ "make_directional_histogram", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__directional__histogram.html", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__directional__histogram" ],
          [ "make_image_source", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__image__source.html", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__image__source" ],
          [ "make_stochastic_histogram", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__stochastic__histogram.html", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__stochastic__histogram" ],
          [ "make_visual", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__visual.html", "classwayverb_1_1raytracer_1_1reflection__processor_1_1make__visual" ],
          [ "stochastic_histogram", "classwayverb_1_1raytracer_1_1reflection__processor_1_1stochastic__histogram.html", "classwayverb_1_1raytracer_1_1reflection__processor_1_1stochastic__histogram" ],
          [ "visual", "classwayverb_1_1raytracer_1_1reflection__processor_1_1visual.html", "classwayverb_1_1raytracer_1_1reflection__processor_1_1visual" ]
        ] ],
        [ "stochastic", null, [
          [ "dirac_sequence", "structwayverb_1_1raytracer_1_1stochastic_1_1dirac__sequence.html", "structwayverb_1_1raytracer_1_1stochastic_1_1dirac__sequence" ],
          [ "directional_energy_histogram", "structwayverb_1_1raytracer_1_1stochastic_1_1directional__energy__histogram.html", "structwayverb_1_1raytracer_1_1stochastic_1_1directional__energy__histogram" ],
          [ "energy_histogram", "structwayverb_1_1raytracer_1_1stochastic_1_1energy__histogram.html", "structwayverb_1_1raytracer_1_1stochastic_1_1energy__histogram" ],
          [ "finder", "classwayverb_1_1raytracer_1_1stochastic_1_1finder.html", "classwayverb_1_1raytracer_1_1stochastic_1_1finder" ],
          [ "program", "classwayverb_1_1raytracer_1_1stochastic_1_1program.html", "classwayverb_1_1raytracer_1_1stochastic_1_1program" ],
          [ "size_functor", "structwayverb_1_1raytracer_1_1stochastic_1_1size__functor.html", "structwayverb_1_1raytracer_1_1stochastic_1_1size__functor" ]
        ] ],
        [ "attenuate_mapper", "structwayverb_1_1raytracer_1_1attenuate__mapper.html", "structwayverb_1_1raytracer_1_1attenuate__mapper" ],
        [ "attenuated_impulse", "structwayverb_1_1raytracer_1_1attenuated__impulse.html", "structwayverb_1_1raytracer_1_1attenuated__impulse" ],
        [ "canonical_results", "structwayverb_1_1raytracer_1_1canonical__results.html", "structwayverb_1_1raytracer_1_1canonical__results" ],
        [ "dirac_sum_functor", "structwayverb_1_1raytracer_1_1dirac__sum__functor.html", "structwayverb_1_1raytracer_1_1dirac__sum__functor" ],
        [ "get_results_functor_adapter", "classwayverb_1_1raytracer_1_1get__results__functor__adapter.html", "classwayverb_1_1raytracer_1_1get__results__functor__adapter" ],
        [ "histogram_mapper", "structwayverb_1_1raytracer_1_1histogram__mapper.html", "structwayverb_1_1raytracer_1_1histogram__mapper" ],
        [ "impulse", "structwayverb_1_1raytracer_1_1impulse.html", "structwayverb_1_1raytracer_1_1impulse" ],
        [ "item_with_time", "structwayverb_1_1raytracer_1_1item__with__time.html", "structwayverb_1_1raytracer_1_1item__with__time" ],
        [ "iterative_builder", "classwayverb_1_1raytracer_1_1iterative__builder.html", "classwayverb_1_1raytracer_1_1iterative__builder" ],
        [ "make_get_results_functor_adapter", "structwayverb_1_1raytracer_1_1make__get__results__functor__adapter.html", "structwayverb_1_1raytracer_1_1make__get__results__functor__adapter" ],
        [ "make_process_functor_adapter", "structwayverb_1_1raytracer_1_1make__process__functor__adapter.html", "structwayverb_1_1raytracer_1_1make__process__functor__adapter" ],
        [ "multitree", "structwayverb_1_1raytracer_1_1multitree.html", "structwayverb_1_1raytracer_1_1multitree" ],
        [ "process_functor_adapter", "classwayverb_1_1raytracer_1_1process__functor__adapter.html", "classwayverb_1_1raytracer_1_1process__functor__adapter" ],
        [ "program", "classwayverb_1_1raytracer_1_1program.html", "classwayverb_1_1raytracer_1_1program" ],
        [ "reflection", "structwayverb_1_1raytracer_1_1reflection.html", "structwayverb_1_1raytracer_1_1reflection" ],
        [ "reflector", "classwayverb_1_1raytracer_1_1reflector.html", "classwayverb_1_1raytracer_1_1reflector" ],
        [ "simulation_parameters", "structwayverb_1_1raytracer_1_1simulation__parameters.html", "structwayverb_1_1raytracer_1_1simulation__parameters" ],
        [ "simulation_results", "structwayverb_1_1raytracer_1_1simulation__results.html", "structwayverb_1_1raytracer_1_1simulation__results" ],
        [ "sinc_sum_functor", "structwayverb_1_1raytracer_1_1sinc__sum__functor.html", "structwayverb_1_1raytracer_1_1sinc__sum__functor" ],
        [ "stochastic_path_info", "structwayverb_1_1raytracer_1_1stochastic__path__info.html", "structwayverb_1_1raytracer_1_1stochastic__path__info" ],
        [ "time_functor", "structwayverb_1_1raytracer_1_1time__functor.html", "structwayverb_1_1raytracer_1_1time__functor" ]
      ] ],
      [ "waveguide", null, [
        [ "postprocessor", null, [
          [ "directional_receiver", "classwayverb_1_1waveguide_1_1postprocessor_1_1directional__receiver.html", "classwayverb_1_1waveguide_1_1postprocessor_1_1directional__receiver" ],
          [ "node", "classwayverb_1_1waveguide_1_1postprocessor_1_1node.html", "classwayverb_1_1waveguide_1_1postprocessor_1_1node" ]
        ] ],
        [ "preprocessor", null, [
          [ "gaussian", "classwayverb_1_1waveguide_1_1preprocessor_1_1gaussian.html", "classwayverb_1_1waveguide_1_1preprocessor_1_1gaussian" ],
          [ "hard_source", "classwayverb_1_1waveguide_1_1preprocessor_1_1hard__source.html", "classwayverb_1_1waveguide_1_1preprocessor_1_1hard__source" ],
          [ "soft_source", "classwayverb_1_1waveguide_1_1preprocessor_1_1soft__source.html", "classwayverb_1_1waveguide_1_1preprocessor_1_1soft__source" ]
        ] ],
        [ "attenuate_mapper", "structwayverb_1_1waveguide_1_1attenuate__mapper.html", "structwayverb_1_1waveguide_1_1attenuate__mapper" ],
        [ "band", "structwayverb_1_1waveguide_1_1band.html", "structwayverb_1_1waveguide_1_1band" ],
        [ "bandpass_band", "structwayverb_1_1waveguide_1_1bandpass__band.html", "structwayverb_1_1waveguide_1_1bandpass__band" ],
        [ "biquad_coefficients_array", "structwayverb_1_1waveguide_1_1biquad__coefficients__array.html", "structwayverb_1_1waveguide_1_1biquad__coefficients__array" ],
        [ "biquad_memory_array", "structwayverb_1_1waveguide_1_1biquad__memory__array.html", "structwayverb_1_1waveguide_1_1biquad__memory__array" ],
        [ "boundary_coefficient_program", "classwayverb_1_1waveguide_1_1boundary__coefficient__program.html", "classwayverb_1_1waveguide_1_1boundary__coefficient__program" ],
        [ "boundary_data", "structwayverb_1_1waveguide_1_1boundary__data.html", "structwayverb_1_1waveguide_1_1boundary__data" ],
        [ "boundary_data_array", "structwayverb_1_1waveguide_1_1boundary__data__array.html", "structwayverb_1_1waveguide_1_1boundary__data__array" ],
        [ "boundary_index_array", "structwayverb_1_1waveguide_1_1boundary__index__array.html", "structwayverb_1_1waveguide_1_1boundary__index__array" ],
        [ "boundary_index_data", "structwayverb_1_1waveguide_1_1boundary__index__data.html", "structwayverb_1_1waveguide_1_1boundary__index__data" ],
        [ "coefficients", "structwayverb_1_1waveguide_1_1coefficients.html", "structwayverb_1_1waveguide_1_1coefficients" ],
        [ "compressed_rectangular_waveguide", "classwayverb_1_1waveguide_1_1compressed__rectangular__waveguide.html", "classwayverb_1_1waveguide_1_1compressed__rectangular__waveguide" ],
        [ "compressed_rectangular_waveguide_program", "classwayverb_1_1waveguide_1_1compressed__rectangular__waveguide__program.html", "classwayverb_1_1waveguide_1_1compressed__rectangular__waveguide__program" ],
        [ "condensed_node", "structwayverb_1_1waveguide_1_1condensed__node.html", "structwayverb_1_1waveguide_1_1condensed__node" ],
        [ "filter_descriptor", "structwayverb_1_1waveguide_1_1filter__descriptor.html", "structwayverb_1_1waveguide_1_1filter__descriptor" ],
        [ "frequency_domain_envelope", "classwayverb_1_1waveguide_1_1frequency__domain__envelope.html", "classwayverb_1_1waveguide_1_1frequency__domain__envelope" ],
        [ "memory", "structwayverb_1_1waveguide_1_1memory.html", "structwayverb_1_1waveguide_1_1memory" ],
        [ "mesh", "classwayverb_1_1waveguide_1_1mesh.html", "classwayverb_1_1waveguide_1_1mesh" ],
        [ "mesh_descriptor", "structwayverb_1_1waveguide_1_1mesh__descriptor.html", "structwayverb_1_1waveguide_1_1mesh__descriptor" ],
        [ "multiple_band_constant_spacing_parameters", "structwayverb_1_1waveguide_1_1multiple__band__constant__spacing__parameters.html", "structwayverb_1_1waveguide_1_1multiple__band__constant__spacing__parameters" ],
        [ "offset_signal", "structwayverb_1_1waveguide_1_1offset__signal.html", "structwayverb_1_1waveguide_1_1offset__signal" ],
        [ "program", "classwayverb_1_1waveguide_1_1program.html", "classwayverb_1_1waveguide_1_1program" ],
        [ "setup_program", "classwayverb_1_1waveguide_1_1setup__program.html", "classwayverb_1_1waveguide_1_1setup__program" ],
        [ "single_band_parameters", "structwayverb_1_1waveguide_1_1single__band__parameters.html", "structwayverb_1_1waveguide_1_1single__band__parameters" ],
        [ "vectors", "classwayverb_1_1waveguide_1_1vectors.html", "classwayverb_1_1waveguide_1_1vectors" ],
        [ "voxels_and_mesh", "structwayverb_1_1waveguide_1_1voxels__and__mesh.html", "structwayverb_1_1waveguide_1_1voxels__and__mesh" ]
      ] ]
    ] ],
    [ "bracketer", "classbracketer.html", "classbracketer" ],
    [ "dir", "classdir.html", "classdir" ],
    [ "ImpulseGenerator", "class_impulse_generator.html", "class_impulse_generator" ],
    [ "InputGenerator", "class_input_generator.html", "class_input_generator" ],
    [ "nested", "structnested.html", "structnested" ],
    [ "NoiseGenerator", "class_noise_generator.html", "class_noise_generator" ],
    [ "non_trivial", "classnon__trivial.html", "classnon__trivial" ],
    [ "Point3", "struct_point3.html", "struct_point3" ],
    [ "program", "classprogram.html", "classprogram" ],
    [ "QuietNoiseGenerator", "class_quiet_noise_generator.html", "class_quiet_noise_generator" ],
    [ "really_basic_scene", "structreally__basic__scene.html", "structreally__basic__scene" ],
    [ "Triangle3", "struct_triangle3.html", "struct_triangle3" ],
    [ "troublesome", "structtroublesome.html", "structtroublesome" ],
    [ "Type", "struct_type.html", null ]
];